whisper_model: "base.en"  # Specify the Whisper model
llama_model: "llama-3.2"  # Llama 3.2 model
use_gpu: false  # Set to false if no GPU available
tts_engine: "pyttsx3"  # Choose between pyttsx3 and Bark
